name: 2025-06-20-hsf-iris-hep-uproot-awkward-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyarrow==20.0.0
  - numpy==2.3.0
  - matplotlib==3.10.3
  - pandas==2.3.0
  - hist==2.8.1
  - numba==0.61.2
  - xrootd==5.8.1
  - root==6.34.4
  - tbb-devel==2022.1.0
  - zstandard==0.23.0
  - lz4==4.4.4
  - python-xxhash==3.5.0
  - pip==25.1.1
  - awkward==2.8.3
  - awkward-cpp==46
  - uproot==5.6.2
  - vector==1.6.2
  - particle==0.25.4
